"""empty message

Revision ID: 71006ee56f1f
Revises: e73f50832779
Create Date: 2020-03-26 23:00:48.709853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71006ee56f1f'
down_revision = 'e73f50832779'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('country', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'country')
    # ### end Alembic commands ###
