"""empty message

Revision ID: 981934ae2767
Revises: b019b5e91086
Create Date: 2020-03-30 10:29:56.895940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '981934ae2767'
down_revision = 'b019b5e91086'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('degrees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('degreeName', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_degrees',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('degree_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['degree_id'], ['degrees.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'degree_id')
    )
    op.drop_table('user_tags')
    op.drop_table('tags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('tags_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('tagName', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='tags_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('user_tags',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name='user_tags_tag_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_tags_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'tag_id', name='user_tags_pkey')
    )
    op.drop_table('user_degrees')
    op.drop_table('degrees')
    # ### end Alembic commands ###
